### ISSUE TITLE
french quotqtion marks (« ») replaced by < >

### ISSUE THREAD

**Issue by birdy4012** [wiris/moodle-filter_wiris#28]
Hi,
since 4.9.0.1380 (or maybe before), in Atto editor, french quotation marks (« ») replaced by < >when we save, or just when we switch view with the HTML button.
We have updated plugin to 4.11.0.1383, and problem is still present.
When we remove wiris button (row "_math = wiris_" in "_editor_atto | toolbar_" parameter), we don't have problem anymore.

**Comment by manuelwiris** [comment]
@birdy4012 

Thanks for your feedback. We are able to reproduce the bug in our end. The issue was added into our tracker. 

WIRIS uses french quotations marks instead of "<" and ">" to store MathML in Moodle database because Moodle stripe tags in MathML . Inside the  HTML view we replace french quotation marks for "<" or ">" to allow user to see standard MathML. Seems that we are not checking properly if the parsed text is a MathML. You can read more about this encoding here: http://www.wiris.com/en/plugins/docs/resources/encoding-attributes

Best,

**Comment by raunolipp** [comment]
Hi,  
we have the same problem with §.  
Are you planning to do context check for all the encoded characters?

**Comment by manuelwiris** [comment]
@raunolipp We will include this issue in our March sprint. We will check all the encoded characters in order to avoid this problem. We will get back to you once the new version is available

**Comment by manuelwiris** [comment]
@raunolipp 

Unfortunately, we can't reproduce this issue on our end, Please could you provide a detailed description? Can you reproduce this issue with the latest version (7.0.0)

Thanks in advance.

**Comment by raunolipp** [comment]
It magically works now after upgrading from moodle 3.3.4 to 3.3.5
We use the 7.0.0 version

**Comment by manuelwiris** [comment]
@raunolipp seems a cache problem, caches are purged on Moodle updates. 

I mark this issue as closes. Thanks for your feedback
