### ISSUE TITLE
FR: Option to disable converting MathML to image

### ISSUE THREAD

**Issue by danowar2k** [wiris/moodle-filter_wiris#93]
Wiris helps in storing MathML to the database by converting MathML to SafeXML so that Moodle's HMTLPurifier doesn't clean the math tags before storing to database.

Wiris then also converts the SafeXML to regular MathML (at least I presume it does) before requesting an image from the Wiris servers for the converted formula.

To be able to use Moodle's MathJax filter instead for displaying the MathML formula, it would be nice to have the option to disable replacing the MathML with the image HTML.

If disabled, the filter would just output the MathML so that other filters can postprocess it.

Would that be possible?

**Comment by dcanet-at-wiris** [comment]
Hola. @danowar2k 

First of all, sorry for our late answer and thanks for reaching us.

If I am getting you right I am explaining below the expected behaviour you are asking for.

Have a look please, so we can start considering it with the rest of the team. 😃  

## Description (draft)
To be able to use Moodle's MathJax filter instead for displaying the MathML formula, it would be nice to have the option to disable replacing the MathML with the image HTML.

If disabled, the filter would output the SafeXML to MathML so that other filters can postprocess it.

## Steps to reproduce

1. Go to MathType filter settings
2. Activate a new feature to render to MathML format instead of SafeXML
2. Add a Moodle's content, a page for example
2. Add a title
3. Add a math formula using MathType
4. Click "Save and continue"

## Expected result

* The page is shown and the formula is rendered as an image either by the browser or by the MathJax filter.

## Other details

Same content on different formats:

**MathML**:

````xml
<math> 
<mrow>
  <mfrac>
    <mi>a</mi>
    <mrow>
      <mi>b</mi>
      <mo>/</mo>
      <mn>2</mn>
    </mrow>
  </mfrac>
</mrow>
</math>
````

**SafeXML**:

````text
«math xmlns=¨http://www.w3.org/1998/Math/MathML¨»«mfrac»«mi»a«/mi»«mrow»«mi»b«/mi»«mo»/«/mo»«mn»2«/mn»«/mrow»«/mfrac»«/math»
````

**Formula as an image rendered with MathType flter API**:

![formula-rendered-using-mathtype-filter](https://user-images.githubusercontent.com/85346791/152513010-b693314f-e6a9-4014-a754-198efc11e1e8.png)

**Formula rendered with MathJax**

![image](https://user-images.githubusercontent.com/85346791/152514789-d2ff82f6-a1d0-409b-b044-daeb0828daeb.png)

**Comment by dcanet-at-wiris** [comment]
Hi, @danowar2k

I've been discussing your question with the rest of the team and we are not planning to implement this behaviour, soon.

Nevertheless, we will register this feature request on our backlog so we can discuss it further and consider it on future releases.

Thanks for reaching us.

Kind regards,

D.
